* Tweaked a style setting
git-svn-id: https://svn.tools.ietf.org/svn/src/rfcdiff@45 b09da908-5413-0410-be69-a971d00a7ddb

diff --git a/rfcdiff b/rfcdiff
--- a/rfcdiff
+++ b/rfcdiff
@@ -93,7 +93,11 @@
 #
 # Log:
 #			
-#	06 Jan 2005	v1.21 - tweaked a style setting	
+#	06 Jan 2005	v1.22 - Tweaked a style setting	
+#			
+#	10 Dec 2004	v1.21 - Added anchor for each diff, in order	
+#			for it to be possible to create URLs refering
+#			to individual diffs.
 #			
 #	09 Dec 2004	v1.20 -	fixed the same bug again, a bit better
 #			this time :-)
@@ -237,7 +241,7 @@
 # End:
 #
 
-export version="1.21"
+export version="1.22"
 export prelines="10"
 export basename=$(basename $0)
 export workdir="/tmp/$basename-$$"
@@ -400,6 +404,7 @@ function header(file1, file2) {
    printf "" \
 "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> \n" \
 "<!-- Generated by rfcdiff %s: rfcdiff %s --> \n" \
+"<!-- <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional\" > -->\n" \
 "<!-- System: %s --> \n" \
 "<!-- Using awk: %s: %s --> \n" \
 "<!-- Using diff: %s: %s --> \n" \
@@ -412,18 +417,17 @@ function header(file1, file2) {
 "  <style type=\"text/css\"> \n" \
 "    body    { margin: 0.4ex; margin-right: auto; } \n" \
 "    tr      { } \n" \
-"    td      { white-space: pre; font-family: monospace; vertical-align: top; } \n" \
+"    td      { white-space: pre; font-family: monospace; vertical-align: top; font-size: 9pt;} \n" \
 "    th      { font-size: 11pt; } \n" \
-"    small   { font-family: Verdana, Helvetica, sans-serif; } \n" \
-"    .small  { font-size: 8pt; } \n" \
+"    .small  { font-size: 7pt; font-style: italic; font-family: Verdana, Helvetica, sans-serif; } \n" \
 "    .left   { background-color: #EEE; } \n" \
 "    .right  { background-color: #FFF; } \n" \
-"    .diff   { background-color: lightblue; } \n" \
+"    .diff   { background-color: #CCF; } \n" \
 "    .lblock { background-color: #BFB; } \n" \
 "    .rblock { background-color: #FF8; } \n" \
-"    .insert { background-color: cyan; } \n" \
+"    .insert { background-color: #8FF; } \n" \
 "    .delete { background-color: #ACF; } \n" \
-"    .void   { background-color: lightyellow; } \n" \
+"    .void   { background-color: #FFB; } \n" \
 "    .cont   { background-color: #EEE; } \n" \
 "    .linebr { background-color: #AAA; } \n" \
 "    .lineno { color: red; background-color: #FFF; font-size: 8pt; text-align: right; padding: 0 2px; } \n" \
@@ -491,9 +495,8 @@ function fixesc(line) {
     return line;
 }
 
-function chunkdiff() {
+function chunkdiff(chunk) {
    if (difflines1 == 0 && difflines2 == 0) return;
-   chunk++;
 
    chunkfile1= sprintf("1/chunk%04d", chunk);
    chunkfile2= sprintf("2/chunk%04d", chunk);
@@ -517,45 +520,52 @@ function chunkdiff() {
 }
 
 function flush() {
-   multiline = (difflines1 > 1) || (difflines2 > 1);
-   if (multiline && (wdiff != "")) chunkdiff();
+   if (difflines1 || difflines2) {
+      difftag++;
+      multiline = (difflines1 > 1) || (difflines2 > 1);
+      if (multiline && (wdiff != "")) chunkdiff(difftag);
 
-   for (l = 0; l < difflines1 || l < difflines2; l++) {
-      if (l in stack1) {
-	 line1 = stack1[l];
-	 delete stack1[l];
-	 linenum1++
-	 if (line1 == "")
-	    if (optwidth > 0) {
-		line1 = substr("                                                                                                                                                                ",0,optwidth);
-	    } else {
-		line1 = "                                                                         ";
-	    }
-      } else {
-	 line1 = "";
-      }
-      if (l in stack2) {
-	 line2 = stack2[l];
-	 delete stack2[l];
-	 linenum2++;
-	 if (line2 == "")
-	    if (optwidth > 0) {
-		line2 = substr("                                                                                                                                                                ",0,optwidth);
-	    } else {
-		line2 = "                                                                         ";
-	    }
-      } else {
-	 line2 = "";
-      }
+      printf "      <tr><td><a name=\"diff%04d\" /></td></tr>\n", difftag;
+      for (l = 0; l < difflines1 || l < difflines2; l++) {
+	 if (l in stack1) {
+	    line1 = stack1[l];
+	    delete stack1[l];
+	    linenum1++
+	    if (line1 == "")
+	       if (optwidth > 0) {
+		   line1 = substr("                                                                                                                                                                ",0,optwidth);
+	       } else {
+		   line1 = "                                                                         ";
+	       }
+	 } else {
+	    line1 = "";
+	 }
+	 if (l in stack2) {
+	    line2 = stack2[l];
+	    delete stack2[l];
+	    linenum2++;
+	    if (line2 == "")
+	       if (optwidth > 0) {
+		   line2 = substr("                                                                                                                                                                ",0,optwidth);
+	       } else {
+		   line2 = "                                                                         ";
+	       }
+	 } else {
+	    line2 = "";
+	 }
 
-      if (!multiline || (wdiff == "")) {
-	 worddiff(line1, line2);
-	 line1 = fixesc(sprintf("%s<span class=\"delete\">%s</span>%s", wordpart[0], wordpart[1], wordpart[3]));
-	 line2 = fixesc(sprintf("%s<span class=\"insert\">%s</span>%s", wordpart[0], wordpart[2], wordpart[3]))
+	 if (!multiline || (wdiff == "")) {
+	    worddiff(line1, line2);
+	    line1 = fixesc(sprintf("%s<span class=\"delete\">%s</span>%s", wordpart[0], wordpart[1], wordpart[3]));
+	    line2 = fixesc(sprintf("%s<span class=\"insert\">%s</span>%s", wordpart[0], wordpart[2], wordpart[3]));
+	    # Clean up; remove empty spans
+	    sub(/<span class="delete"><\/span>/,"", line1);
+	    sub(/<span class="insert"><\/span>/,"", line2);
+	 }
+	 left  = sprintf("<td class=\"lineno\" valign=\"top\">%s</td><td class=\"lblock\">%s</td>", numdisplay(1, linenum1), line1);
+	 right = sprintf("<td class=\"rblock\">%s</td><td class=\"lineno\" valign=\"top\">%s</td>", line2, numdisplay(2, linenum2));
+	 printf "      <tr>%s<td> </td>%s</tr>\n", left, right;
       }
-      left  = sprintf("<td class=\"lineno\" valign=\"top\">%s</td><td class=\"lblock\">%s</td>", numdisplay(1, linenum1), line1);
-      right = sprintf("<td class=\"rblock\">%s</td><td class=\"lineno\" valign=\"top\">%s</td>", line2, numdisplay(2, linenum2));
-      printf "      <tr>%s<td> </td>%s</tr>\n", left, right;
    }
 }
 
@@ -622,15 +632,15 @@ function maybebreakline(line,    width) {
 	      page1 = getpage(1,linenum1);
 	      page2 = getpage(2,linenum2);
 	      if (page1 == "?") {
-		 posinfo1 = sprintf("<a name=\"diff-%s\" /><small>skipping to change at</small><em> line %s</em>", diffnum, getpageline(1, linenum1, page1));
+		 posinfo1 = sprintf("<a name=\"part-l%s\" /><small>skipping to change at</small><em> line %s</em>", diffnum, getpageline(1, linenum1, page1));
 	      } else {
-		 posinfo1 = sprintf("<a name=\"diff-%s\" /><small>skipping to change at</small><em> page %s, line %s</em>", diffnum, page1, getpageline(1, linenum1, page1));
+		 posinfo1 = sprintf("<a name=\"part-l%s\" /><small>skipping to change at</small><em> page %s, line %s</em>", diffnum, page1, getpageline(1, linenum1, page1));
 	      }
 
 	      if (page2 == "?") {
-		 posinfo2 = sprintf("<a name=\"diff-%s\" /><small>skipping to change at</small><em> line %s</em>", diffnum, getpageline(2, linenum2, page2));
+		 posinfo2 = sprintf("<a name=\"part-r%s\" /><small>skipping to change at</small><em> line %s</em>", diffnum, getpageline(2, linenum2, page2));
 	      } else {
-		 posinfo2 = sprintf("<a name=\"diff-%s\" /><small>skipping to change at</small><em> page %s, line %s</em>", diffnum, page2, getpageline(2, linenum2, page2));
+		 posinfo2 = sprintf("<a name=\"part-r%s\" /><small>skipping to change at</small><em> page %s, line %s</em>", diffnum, page2, getpageline(2, linenum2, page2));
 	      }
 
 	      printf "      <tr bgcolor=\"gray\" ><td></td><th>%s</th><th> </th><th>%s</th><td></td></tr>\n", posinfo1, posinfo2;
@@ -671,7 +681,7 @@ END	{
 	   printf("\n" \
 "     <tr><td></td><td class=\"left\"></td><td> </td><td class=\"right\"></td><td></td></tr>\n" \
 "     <tr bgcolor=\"gray\"><th colspan=\"5\" align=\"center\"><a name=\"end\">&nbsp;%s&nbsp;</a></th></tr>\n" \
-"     <tr><td colspan=\"5\" align=\"center\"><br/><small><small><i>This html diff was produced by rfcdiff %s, available from <a href=\"http://www.levkowetz.com/ietf/tools/rfcdiff/\" >http://www.levkowetz.com/ietf/tools/rfcdiff/</a> </i></small></small></td></tr>\n" \
+"     <tr><td colspan=\"5\" align=\"center\" class=\"small\"><br/>This html diff was produced by rfcdiff %s, available from <a href=\"http://www.levkowetz.com/ietf/tools/rfcdiff/\" >http://www.levkowetz.com/ietf/tools/rfcdiff/</a> </td></tr>\n" \
 "   </table>\n" \
 "   </body>\n" \
 "   </html>\n", diffnum?"End of changes.":"No changes.", ENVIRON["version"]);
